SB_CONFIG_SECURE_BOOT_APPCORE=y
#SB_CONFIG_SECURE_BOOT_SIGNING_KEY_FILE="keys/root-ed25519.pem"
SB_CONFIG_SECURE_BOOT_GENERATE_DEFAULT_KMU_KEYFILE=y
#SB_CONFIG_SECURE_BOOT_PUBLIC_KEY_FILES="keys/pub.pem"
